Feature/questionnaire fix
Ecodenl/Woningdossier pull request #674
Opened 2021-01-26 13:38 UTC by Yinci

Check whether we need to add extra logic to the questionnaire page (e.g. adding new fields manually)

2021-02-03 12:35 UTC, Yinci commented
This PR makes the following changes:

- All `@lang` translations have been moved from `woningdossier.php` to its own lang file
- Validation has been added to check whether question options are empty or not; this is required to stop exceptions happening when adding questions with options (`index options is undefined`)
- QoL changes to the editor; 
  - Add-validation button disappears when clicked, so no more than one can be added (only 1 is currently supported)
  - Validation can be removed
  - An add-option button has been added to questions that can have options, to manually allow the user to add new options
  - Index logic updates when deleting an option
  - If validation fails, previously added questions, options, validation, etc. get rebuild
  - If validation fails, the inputs on which it failed will now be highlighted
  - Validation errors are now properly translated
- Split off the JS into a separate part
- Javascript refactor, to be more consistent, and allow for easier maintenance
- Javascript now uses `@lang` as well.
- LanguageRequired rule to allow easy checks of locale input
- Removed unused parts

2021-02-03 15:27 UTC, Yinci commented
- Added a test to test for a question with an option

2021-02-05 10:26 UTC, frogeyedman requested changes

2021-02-05 10:26 UTC, frogeyedman commented on composer.lock
> +    "content-hash": "766b1653d7c8aa13cecf2fda0dcbec15",
Composer update should be reverted

2021-02-05 10:33 UTC, frogeyedman requested changes
A radio button question does not give a validation error when its supposed to.

- Add a new radio button question
- Leave the question name empty, but fill in the options
- Save the questionnaire

2021-02-09 10:13 UTC, frogeyedman approved these changes
Seems ok.

2021-12-24 08:23 UTC, frogeyedman commented
@Yinci could you solve the conflicts and or check if still relevant ?

2021-12-24 08:24 UTC, Yinci commented
Potentially rewrite this using Livewire and AlpineJS now develop has been upgraded. Definitely requires checking if still functional if not going to be rewritten.

2022-07-27 08:48 UTC, frogeyedman commented
Closing PR because author states upgrade with alpine js / livewire is better, which i support. Also has a bug shown on the test environment.

2022-07-27 08:48 UTC, closed without merging